export const formData = [
  {
    name: "firstName",
    question: "What's your first name?",
    value: "",
    required: true,
    type: "text",
    initalState: "",
  },
  {
    name: "lastName",
    question: "What's your last name?",
    value: "",
    required: true,
    regex: "",
    type: "text",
    initalState: "",
  },
  {
    name: "industry",
    question: "What industry is your company in?",
    value: "",
    required: true,
    regex: "",
    type: "select",
    initalState: "",
  },
  {
    name: "role",
    question: "Your role in your company?",
    value: "",
    required: true,
    regex: "",
    type: "checkbox",
    initalState: "",
  },
  {
    name: "goal",
    question: "what's your professional goal for the next 12 months?",
    value: "",
    required: true,
    regex: "",
    type: "checkbox",
    initalState: "",
  },
  {
    name: "email",
    question: "Email you'd like to register with?",
    value: "",
    required: true,
    regex: "",
    type: "text",
    initalState: "",
  },
];
