export const formData = [
  {
    name: "startPage",
    question: "",
    value: "",
    required: false,
    fieldType: "infoPage",
    type: "",
    initalState: "",
  },
  {
    name: "firstName",
    question: "What's your first name?",
    value: "",
    required: true,
    fieldType: "input",
    type: "text",
    initalState: "",
  },
  {
    name: "lastName",
    question: "What's your last name?",
    value: "",
    required: true,
    regex: "",
    fieldType: "input",
    type: "text",
    initalState: "",
  },
  {
    name: "industry",
    question: "What industry is your company in?",
    value: "",
    required: true,
    regex: "",
    fieldType: "select",
    type: "text",
    initalState: "",
  },
  {
    name: "role",
    question: "Your role in your company?",
    value: "",
    required: true,
    regex: "",
    fieldType: "input",
    type: "radio",
    initalState: "",
  },
  {
    name: "goal",
    question: "what's your professional goal for the next 12 months?",
    value: "",
    required: true,
    regex: "",
    fieldType: "input",
    type: "checkbox",
    initalState: "",
  },
  {
    name: "email",
    question: "Email you'd like to register with?",
    value: "",
    required: true,
    regex: "",
    fieldType: "input",
    type: "text",
    initalState: "",
  },
  {
    name: "Phone",
    question: "Your phone number",
    value: "",
    required: true,
    regex: "",
    fieldType: "input",
    type: "text",
    initalState: "",
  },
  {
    name: "endPage",
    question: "All done! Thanks for your time.",
    value: "",
    required: false,
    regex: "",
    fieldType: "",
    type: "",
    initalState: "",
  },
];
